import { getCurrentCalendarMonth } from "@/src/features/finance/dates";
import type { Account, Budget, Category, FinanceDataset, SavingsGoal, Transaction } from "@/src/features/finance/types";

const currency = "BDT";
const month = getCurrentCalendarMonth();
const yearMonth = month.start.slice(0, 7);
const monthEndDay = Number(month.end.slice(8, 10));

function date(day: number) {
  return `${yearMonth}-${`${Math.min(day, monthEndDay)}`.padStart(2, "0")}`;
}

function created(day: number) {
  return `${date(day)}T09:00:00`;
}

const accounts: Account[] = [
  {
    id: "cash",
    name: "Cash",
    type: "cash",
    currency,
    openingBalanceMinor: 350000,
    isSavings: false,
    isArchived: false,
    createdAt: created(1),
  },
  {
    id: "main-bank",
    name: "Main bank account",
    type: "bank",
    currency,
    openingBalanceMinor: 18000000,
    isSavings: false,
    isArchived: false,
    createdAt: created(1),
  },
  {
    id: "bkash",
    name: "bKash",
    type: "mobile_wallet",
    currency,
    openingBalanceMinor: 120000,
    isSavings: false,
    isArchived: false,
    createdAt: created(1),
  },
  {
    id: "savings-bank",
    name: "Savings account",
    type: "savings",
    currency,
    openingBalanceMinor: 6200000,
    isSavings: true,
    isArchived: false,
    createdAt: created(1),
  },
  {
    id: "credit-card",
    name: "Credit card",
    type: "credit_card",
    currency,
    openingBalanceMinor: 800000,
    isSavings: false,
    isArchived: false,
    createdAt: created(1),
  },
];

const categories: Category[] = [
  { id: "salary", name: "Salary", kind: "income" },
  { id: "freelance", name: "Freelance", kind: "income" },
  { id: "business", name: "Business", kind: "income" },
  { id: "gift", name: "Gift", kind: "income" },
  { id: "other-income", name: "Other income", kind: "income" },
  { id: "food", name: "Food", kind: "expense" },
  { id: "transport", name: "Transport", kind: "expense" },
  { id: "housing", name: "Housing", kind: "expense" },
  { id: "bills", name: "Bills", kind: "expense" },
  { id: "healthcare", name: "Healthcare", kind: "expense" },
  { id: "education", name: "Education", kind: "expense" },
  { id: "shopping", name: "Shopping", kind: "expense" },
  { id: "entertainment", name: "Entertainment", kind: "expense" },
  { id: "family", name: "Family", kind: "expense" },
  { id: "other-expense", name: "Other expense", kind: "expense" },
];

const transactions: Transaction[] = [
  {
    id: "salary-current",
    type: "income",
    amountMinor: 12000000,
    currency,
    accountId: "main-bank",
    categoryId: "salary",
    occurredAt: date(1),
    note: "Monthly salary",
    status: "active",
    createdAt: created(1),
    updatedAt: created(1),
  },
  {
    id: "freelance-current",
    type: "income",
    amountMinor: 3500000,
    currency,
    accountId: "bkash",
    categoryId: "freelance",
    occurredAt: date(6),
    note: "Mobile app maintenance",
    status: "active",
    createdAt: created(6),
    updatedAt: created(6),
  },
  {
    id: "food-current",
    type: "expense",
    amountMinor: 1425000,
    currency,
    accountId: "cash",
    categoryId: "food",
    occurredAt: date(8),
    note: "Groceries and meals",
    status: "active",
    createdAt: created(8),
    updatedAt: created(8),
  },
  {
    id: "transport-current",
    type: "expense",
    amountMinor: 420000,
    currency,
    accountId: "bkash",
    categoryId: "transport",
    occurredAt: date(10),
    note: "Ride sharing and fuel",
    status: "active",
    createdAt: created(10),
    updatedAt: created(10),
  },
  {
    id: "utility-current",
    type: "expense",
    amountMinor: 865000,
    currency,
    accountId: "main-bank",
    categoryId: "bills",
    occurredAt: date(12),
    note: "Electricity and internet",
    status: "active",
    createdAt: created(12),
    updatedAt: created(12),
  },
  {
    id: "shopping-card-current",
    type: "expense",
    amountMinor: 2100000,
    currency,
    accountId: "credit-card",
    categoryId: "shopping",
    occurredAt: date(15),
    note: "Clothing and home supplies",
    status: "active",
    createdAt: created(15),
    updatedAt: created(15),
  },
  {
    id: "transfer-to-savings-current",
    type: "transfer",
    amountMinor: 3000000,
    currency,
    accountId: "main-bank",
    destinationAccountId: "savings-bank",
    occurredAt: date(18),
    note: "Monthly savings contribution",
    status: "active",
    createdAt: created(18),
    updatedAt: created(18),
  },
  {
    id: "withdraw-savings-current",
    type: "transfer",
    amountMinor: 750000,
    currency,
    accountId: "savings-bank",
    destinationAccountId: "main-bank",
    occurredAt: date(21),
    note: "Cash flow top-up",
    status: "active",
    createdAt: created(21),
    updatedAt: created(21),
  },
  {
    id: "credit-card-payment-current",
    type: "transfer",
    amountMinor: 900000,
    currency,
    accountId: "main-bank",
    destinationAccountId: "credit-card",
    occurredAt: date(24),
    note: "Credit card repayment",
    status: "active",
    createdAt: created(24),
    updatedAt: created(24),
  },
  {
    id: "entertainment-cancelled",
    type: "expense",
    amountMinor: 300000,
    currency,
    accountId: "bkash",
    categoryId: "entertainment",
    occurredAt: date(25),
    note: "Cancelled booking",
    status: "cancelled",
    createdAt: created(25),
    updatedAt: created(25),
  },
  {
    id: "food-previous-month",
    type: "expense",
    amountMinor: 500000,
    currency,
    accountId: "cash",
    categoryId: "food",
    occurredAt: "2026-06-20",
    note: "Previous month groceries",
    status: "active",
    createdAt: "2026-06-20T09:00:00",
    updatedAt: "2026-06-20T09:00:00",
  },
];

const budgets: Budget[] = [
  {
    id: "budget-food",
    categoryId: "food",
    periodStart: month.start,
    periodEnd: month.end,
    limitMinor: 2200000,
    currency,
    status: "active",
  },
  {
    id: "budget-transport",
    categoryId: "transport",
    periodStart: month.start,
    periodEnd: month.end,
    limitMinor: 900000,
    currency,
    status: "active",
  },
  {
    id: "budget-shopping",
    categoryId: "shopping",
    periodStart: month.start,
    periodEnd: month.end,
    limitMinor: 1800000,
    currency,
    status: "active",
  },
  {
    id: "budget-entertainment",
    categoryId: "entertainment",
    periodStart: month.start,
    periodEnd: month.end,
    limitMinor: 700000,
    currency,
    status: "active",
  },
];

const savingsGoals: SavingsGoal[] = [
  {
    id: "goal-emergency-fund",
    name: "Emergency Fund",
    targetMinor: 15000000,
    currency,
    linkedAccountId: "savings-bank",
    targetDate: "2027-01-31",
    status: "active",
  },
  {
    id: "goal-new-laptop",
    name: "New Laptop",
    targetMinor: 18000000,
    currency,
    currentAmountMinor: 9200000,
    targetDate: "2026-12-15",
    status: "active",
  },
  {
    id: "goal-travel",
    name: "Travel",
    targetMinor: 12000000,
    currency,
    currentAmountMinor: 4200000,
    targetDate: "2027-04-30",
    status: "active",
  },
];

export const demoFinanceData: FinanceDataset = {
  currency,
  accounts,
  categories,
  transactions,
  budgets,
  savingsGoals,
  forecast: {
    currency,
    availableLiquidCashMinor: 8400000,
    expectedRemainingIncomeMinor: 1800000,
    upcomingFixedExpensesMinor: 1900000,
    remainingVariableBudgetMinor: 2500000,
    debtObligationsMinor: 600000,
    safetyBufferMinor: 2500000,
  },
};
